services:
  - type: web
    name: smartbizz-business-retail-platform
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
